name: meta_chat_viewer
description: "A Flutter project for viewing and managing chat messages. Includes features for searching messages, handling photos, and managing collections."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.20

environment:
  sdk: '>=3.0.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  image_picker: ^1.1.2
  http_parser: ^4.0.0
  shared_preferences: ^2.0.8
  scrollable_positioned_list: ^0.3.5
  flutter_staggered_grid_view: ^0.7.0
  diacritic: ^0.1.3
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  cached_network_image: ^3.0.0
  flutter_native_splash: ^2.3.1
  flutter_plugin_android_lifecycle: ^2.0.17
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  flutter_dotenv: ^5.0.2
  logging: ^1.1.0
  build_runner: ^2.4.9
  photo_view: ^0.15.0
  http: ^1.2.2
  image_gallery_saver_plus: ^4.0.1
  video_player: ^2.8.2
  just_audio: ^0.9.42
  chewie: ^1.8.5
  wakelock_plus: ^1.1.4
  web: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CaskaydiaCove Nerd Font
      fonts:
        - asset: assets/fonts/CaskaydiaCoveNerdFontMono-Light.ttf
          weight: 300
        - asset: assets/fonts/CaskaydiaCoveNerdFontMono-Regular.ttf
          weight: 400
    - family: JetBrainsMono Nerd Font
      fonts:
        - asset: assets/fonts/JetBrainsMonoNerdFont-Regular.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMonoNerdFont-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMonoNerdFont-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMonoNerdFont-BoldItalic.ttf
          weight: 700
          style: italic

  assets:
    - .env

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash/splash.png
  color_dark: "#042a49"
  image_dark: assets/splash/splash_dark.png
  android_12:
    image: assets/splash/splash_android12.png
    icon_background_color: "#42a5f5"
    image_dark: assets/splash/splash_dark_android12.png
    icon_background_color_dark: "#042a49"
